# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/python:3.0-python3.7-appservice
FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt-get install -y python3.8
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN apt-get install -y python3-pip
RUN apt-get install python3.8-distutils -y
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1


RUN pip install azure-storage-blob \
    pip install azure-storage-queue \
    pip install python-dotenv 
RUN apt-get install libpython3.8-dev -y
RUN python3 -m pip install cffi 

COPY . .

ADD /QAR_Decode  /QAR_Decode
RUN python3 setup.py install

RUN apt-get install -q -y --no-install-recommends \
      xorg \
      unzip \
      wget \
      run-one \
      cron \
      curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 
    
# Download the MCR from MathWorks site an install with -mode silent
RUN mkdir /mcr-install && \
    mkdir /opt/mcr && \
    cd /mcr-install && \
    wget --no-check-certificate -q https://ssd.mathworks.com/supportfiles/downloads/R2020b/Release/8/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2020b_Update_8_glnxa64.zip && \
    unzip -q MATLAB_Runtime_R2020b_Update_8_glnxa64.zip && \
    rm -f MATLAB_Runtime_R2020b_Update_8_glnxa64.zip && \
    ./install -destinationFolder /opt/mcr -agreeToLicense yes -mode silent && \
    cd / && \
    rm -rf mcr-install

#Configure environment variables for MCR
ENV LD_LIBRARY_PATH /opt/mcr/v99/runtime/glnxa64:/opt/mcr/v99/bin/glnxa64:/opt/mcr/v99/sys/os/glnxa64:/opt/mcr/v99/extern/bin/glnxa64
ENV XAPPLRESDIR /etc/X11/app-defaults

RUN crontab crontab
#CMD ["crond", "-f"]
